apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostile-tweets-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostile-tweets-ex
  template:
    metadata:
      labels:
        app: hostile-tweets-ex
    spec:
      containers:
      - name: hostile-tweets-ex
        image: yakovthedocker/hostil-tweets-ex:1.1
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-database
        - name: MONGODB_COLLECTION
          value: "soldier_details"